version: "3.9"

networks:
  algalog-network:
    driver: bridge

services:
  algalog-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "p2023p"
    ports:
      - "3326:3326"
    networks:
      - algalog-network

  algalog-api:
    image: kaylanelira/algalog-api
    environment:
      HOST: algalog-mysql
    ports:
      - "8080:8080"
    networks:
      - algalog-network
    depends_on:
      - algalog-mysql